# Jekyll Configuration for Copywriter Website
title: "Копирайтер - Профессиональные тексты для бизнеса"
description: "Создаю продающие тексты для лендингов, коммерческих предложений и контент-маркетинга"
baseurl: ""
url: "https://your-domain.com"
lang: ru

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Site data
author:
  name: "Анна Копирайтер"
  email: "anna@copywriter.ru"
  telegram: "@anna_copywriter"
  
# Navigation
navigation:
  - name: "Главная"
    url: "/"
  - name: "Услуги"
    url: "/services/"
  - name: "Портфолио"
    url: "/portfolio/"
  - name: "Блог"
    url: "/blog/"
  - name: "Обо мне"
    url: "/about/"
  - name: "Контакты"
    url: "/contact/"

# Services data
services:
  - name: "Лендинги"
    price: "$200-500"
    deadline: "5-7 дней"
    description: "Продающие страницы с высокой конверсией"
  - name: "Коммерческие предложения"
    price: "$100-300"
    deadline: "3-5 дней"
    description: "КП, которые приводят к сделкам"
  - name: "Статьи для блога"
    price: "$50-150"
    deadline: "2-3 дня"
    description: "Экспертный контент для привлечения аудитории"
  - name: "SEO-тексты"
    price: "$80-200"
    deadline: "3-4 дня"
    description: "Оптимизированные тексты для поисковых систем"
