- name: "Лендинги"
  description: "Продающие страницы с высокой конверсией"
  price: "$200-500"
  deadline: "3-7 дней"
  features:
    - "Анализ ЦА"
    - "Структура продаж"
    - "CTA-блоки"
    - "Мобильная адаптация"

- name: "Коммерческие предложения"
  description: "Убедительные КП для B2B и B2C"
  price: "$150-300"
  deadline: "2-4 дня"
  features:
    - "Анализ конкурентов"
    - "УТП"
    - "Структура AIDA"
    - "Персонализация"

- name: "SEO-статьи"
  description: "Оптимизированный контент для поисковых систем"
  price: "$50-150"
  deadline: "2-5 дней"
  features:
    - "Сбор семантики"
    - "LSI-слова"
    - "Мета-теги"
    - "Внутренняя перелинковка"

- name: "Тексты на главную"
  description: "Презентация компании и ключевых услуг"
  price: "$100-250"
  deadline: "2-4 дня"
  features:
    - "Позиционирование"
    - "Блоки преимуществ"
    - "Социальные доказательства"
    - "CTA-элементы"

- name: "Тексты об услугах"
  description: "Детальное описание продуктов и сервисов"
  price: "$60-120"
  deadline: "1-3 дня"
  features:
    - "Выгоды и преимущества"
    - "Техническое описание"
    - "Кейсы применения"
    - "FAQ"

- name: "О компании"
  description: "История, миссия и ценности бизнеса"
  price: "$80-150"
  deadline: "2-3 дня"
  features:
    - "Корпоративная история"
    - "Команда"
    - "Достижения"
    - "Социальная ответственность"
